//
//  OrderCreateInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol OrderCreateBusinessLogic {
    func doSomething(withRequestModel requestModel: OrderCreateModels.Something.RequestModel)
}

protocol OrderCreateDataStore {
//     var name: String { get set }
}

class OrderCreateInteractor: OrderCreateBusinessLogic, OrderCreateDataStore {
    // MARK: - Properties
    var presenter: OrderCreatePresentationLogic?
    var worker: OrderCreateWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: OrderCreateModels.Something.RequestModel) {
        worker = OrderCreateWorker()
        worker?.doSomeWork()
        
        let responseModel = OrderCreateModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
