//
//  OrderCreatePresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol OrderCreatePresentationLogic {
    func presentDates(fromResponseModel responseModel: OrderCreateModels.Dates.ResponseModel)
    func presentAddOrder(fromResponseModel responseModel: OrderCreateModels.Order.ResponseModel)
    func presentDepartments(fromResponseModel responseModel: OrderCreateModels.Departments.ResponseModel)
}

class OrderCreatePresenter: OrderCreatePresentationLogic {
    // MARK: - Properties
    weak var viewController: OrderCreateDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .Severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentDates(fromResponseModel responseModel: OrderCreateModels.Dates.ResponseModel) {
        let viewModel = OrderCreateModels.Dates.ViewModel()
        viewController?.displayDates(fromViewModel: viewModel)
    }
    
    func presentAddOrder(fromResponseModel responseModel: OrderCreateModels.Order.ResponseModel) {
        let viewModel = OrderCreateModels.Order.ViewModel(error: responseModel.error)
        viewController?.displayAddOrder(fromViewModel: viewModel)
    }
    
    func presentDepartments(fromResponseModel responseModel: OrderCreateModels.Departments.ResponseModel) {
        let viewModel = OrderCreateModels.Departments.ViewModel()
        viewController?.displayDepartments(fromViewModel: viewModel)
    }
}
