//
//  PriceListShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol PriceListShowBusinessLogic {
    func doSomething(withRequestModel requestModel: PriceListShowModels.Something.RequestModel)
}

protocol PriceListShowDataStore {
//     var name: String { get set }
}

class PriceListShowInteractor: PriceListShowBusinessLogic, PriceListShowDataStore {
    // MARK: - Properties
    var presenter: PriceListShowPresentationLogic?

    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: PriceListShowModels.Something.RequestModel) {
        let responseModel = PriceListShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
