//
//  PriceListShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol PriceListShowPresentationLogic {
    func presentDepartments(fromResponseModel responseModel: PriceListShowModels.Department.ResponseModel)
    func presentDepartmentItems(fromResponseModel responseModel: PriceListShowModels.DepartmentItems.ResponseModel)
}

class PriceListShowPresenter: PriceListShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: PriceListShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Class deinit", event: .Severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentDepartments(fromResponseModel responseModel: PriceListShowModels.Department.ResponseModel) {
        let viewModel = PriceListShowModels.Department.ViewModel()
        viewController?.displayDepartments(fromViewModel: viewModel)
    }
    
    func presentDepartmentItems(fromResponseModel responseModel: PriceListShowModels.DepartmentItems.ResponseModel) {
        let viewModel = PriceListShowModels.DepartmentItems.ViewModel()
        viewController?.displayDepartmentItems(fromViewModel: viewModel)
    }
}
