//
//  FlowControlShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol FlowControlShowPresentationLogic {
    func presentAppWorkingVersion(fromResponseModel responseModel: FlowControlShowModels.Version.ResponseModel)
}

class FlowControlShowPresenter: FlowControlShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: FlowControlShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Class deinit", event: .Severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentAppWorkingVersion(fromResponseModel responseModel: FlowControlShowModels.Version.ResponseModel) {
        let viewModel = FlowControlShowModels.Version.ViewModel(isEqual: responseModel.isEqual)
        viewController?.checkAppWorkingVersion(fromViewModel: viewModel)
    }
}
