//
//  FlowControlShowRouter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol FlowControlShowRoutingLogic {
    func routeToMainShowScene()
    func routeToSignInShowScene()
}

protocol FlowControlShowDataPassing {
    var dataStore: FlowControlShowDataStore? { get }
}

class FlowControlShowRouter: NSObject, FlowControlShowRoutingLogic, FlowControlShowDataPassing {
    // MARK: - Properties
    weak var viewController: FlowControlShowViewController?
    var dataStore: FlowControlShowDataStore?
    
    
    // MARK: - Routing
    func routeToMainShowScene() {
        let storyboard = UIStoryboard(name: "MainShow", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MainShowVC") as! MainShowViewController
        destinationVC.modalTransitionStyle = .crossDissolve
        
        self.navigateToMainShowScene(source: viewController!, destination: destinationVC)
    }
    
    func routeToSignInShowScene() {
        let storyboard = UIStoryboard(name: "SignInShow", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "SignInShowVC") as! SignInShowViewController
        destinationVC.modalTransitionStyle = .crossDissolve
        
        self.navigateToSignInShowScene(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: - Navigation
    func navigateToMainShowScene(source: FlowControlShowViewController, destination: MainShowViewController) {
        source.present(destination, animated: true, completion: nil)
    }
    
    func navigateToSignInShowScene(source: FlowControlShowViewController, destination: SignInShowViewController) {
        source.present(destination, animated: true, completion: nil)
    }

    
    // MARK: - Passing data
//    func passDataToSomewhere(source: FlowControlShowDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
