//
//  FlowControlShowViewController.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol FlowControlShowDisplayLogic: class {
    func displaySomething(fromViewModel viewModel: FlowControlShowModels.Something.ViewModel)
}

class FlowControlShowViewController: UIViewController {
    // MARK: - Properties
    var interactor: FlowControlShowBusinessLogic?
    var router: NSObjectProtocol?
    
    
    // MARK: - IBOutlets
    
    
    // MARK: - Class Initialization
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        setup()
    }
    
    
    // MARK: - Setup
    private func setup() {
        let viewController          =   self
        let interactor              =   FlowControlShowInteractor()
        let presenter               =   FlowControlShowPresenter()
        
        viewController.interactor   =   interactor
        interactor.presenter        =   presenter
        presenter.viewController    =   viewController
    }
    
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewSettingsDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.navigationController?.setNavigationBarHidden(true, animated: false)
        self.routeToNextScene()
    }

    
    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
    }
    
    fileprivate func routeToNextScene() {
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + dispatchTimeDelay * 17) {
            self.performSegue(withIdentifier: "MainShowSegue", sender: nil)
//            self.performSegue(withIdentifier: "SignInShowSegue", sender: nil)
        }
    }
}


// MARK: - FlowControlShowDisplayLogic
extension FlowControlShowViewController: FlowControlShowDisplayLogic {
    func displaySomething(fromViewModel viewModel: FlowControlShowModels.Something.ViewModel) {
        // NOTE: Display the result from the Presenter

    }
}
