//
//  AboutShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol AboutShowBusinessLogic {
    func doSomething(withRequestModel requestModel: AboutShowModels.Something.RequestModel)
}

protocol AboutShowDataStore {
//     var name: String { get set }
}

class AboutShowInteractor: AboutShowBusinessLogic, AboutShowDataStore {
    // MARK: - Properties
    var presenter: AboutShowPresentationLogic?
    var worker: AboutShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: AboutShowModels.Something.RequestModel) {
        worker = AboutShowWorker()
        worker?.doSomeWork()
        
        let responseModel = AboutShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
