//
//  AboutShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol AboutShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: AboutShowModels.Something.ResponseModel)
}

class AboutShowPresenter: AboutShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: AboutShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: AboutShowModels.Something.ResponseModel) {
        let viewModel = AboutShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
