//
//  DeliveryTermsShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 08.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol DeliveryTermsShowPresentationLogic {
    func presentData(fromResponseModel responseModel: DeliveryTermsShowModels.Dates.ResponseModel)
    func presentConfirmDeliveryTerms(fromResponseModel responseModel: DeliveryTermsShowModels.Item.ResponseModel)
}

class DeliveryTermsShowPresenter: DeliveryTermsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: DeliveryTermsShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Class deinit", event: .Severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentData(fromResponseModel responseModel: DeliveryTermsShowModels.Dates.ResponseModel) {
        let viewModel = DeliveryTermsShowModels.Dates.ViewModel()
        viewController?.displayData(fromViewModel: viewModel)
    }
    
    func presentConfirmDeliveryTerms(fromResponseModel responseModel: DeliveryTermsShowModels.Item.ResponseModel) {
        let viewModel = DeliveryTermsShowModels.Item.ViewModel(error: responseModel.error)
        viewController?.displayConfirmDeliveryTerms(fromViewModel: viewModel)
    }
}
