//
//  DeliveryTermsShowModels.swift
//  CleanCase
//
//  Created by msm72 on 08.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum DeliveryTermsShowModels {
    // MARK: - Use cases
    enum Dates {
        struct RequestModel {
            struct DateForPickerView: PickerViewSupport {
                // PickerViewSupport protocol implementation
                var id: Int16
                var title: String
                
                var times: [PickerViewSupport]
            }

            struct TimeForPickerView: PickerViewSupport {
                // PickerViewSupport protocol implementation
                var id: Int16
                var title: String
                
                var bodyDate: String
                var bodyTime: String
                var deliveryDate: String
            }
        }
        
        struct ResponseModel {
        }
        
        struct ViewModel {
        }
    }
    
    enum Item {
        struct RequestModel {
            let comment: String?
        }
        
        struct ResponseModel {
            let error: Error?
            
            init(error: Error? = nil) {
                self.error = error
            }
        }
        
        struct ViewModel {
            let error: Error?
        }
    }
}
