//
//  LeftSideMenuShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Localize_Swift

// MARK: - Business Logic protocols
protocol LeftSideMenuShowBusinessLogic {
    func loadMenuItems(withRequestModel requestModel: LeftSideMenuShowModels.MenuItems.RequestModel)
}

protocol LeftSideMenuShowDataStore {
    var menuItems: [LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem]! { get set }
}

class LeftSideMenuShowInteractor: LeftSideMenuShowBusinessLogic, LeftSideMenuShowDataStore {
    // MARK: - Properties
    var presenter: LeftSideMenuShowPresentationLogic?
    var worker: LeftSideMenuShowWorker?
    
    // LeftSideMenuShowDataStore protocol implementation
    var menuItems: [LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem]!
    
    
    // MARK: - Business logic implementation
    func loadMenuItems(withRequestModel requestModel: LeftSideMenuShowModels.MenuItems.RequestModel) {
        worker = LeftSideMenuShowWorker()
        menuItems = [LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem]()
        
        let itemsTitles = [
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"
        ]
        
        let itemsIcons = [
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"
        ]
        
        let itemsStoryboardIDs = [
            "ShowVC", "ShowVC", "ShowVC", "ShowVC", "ShowVC", "ShowVC", "ShowVC", "ShowVC", "ShowVC", "ShowVC", "ShowVC"
        ]
        
        let itemsStoryboardNames = [
            "Show", "Show", "Show", "Show", "Show", "Show", "Show", "Show", "Show", "Show", "Show"
        ]

        for i in 0..<11 {
            menuItems.append(LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem(title:             itemsTitles[i].localized(),
                                                                                     iconName:          itemsIcons[i],
                                                                                     storyboardID:      itemsStoryboardIDs[i],
                                                                                     storyboardName:    itemsStoryboardNames[i],
                                                                                     cellHeight:        50.0,
                                                                                     cellIdentifier:    "LeftMenuItemCell"))
        }
        
        let responseModel = LeftSideMenuShowModels.MenuItems.ResponseModel()
        presenter?.presentMenuItems(fromResponseModel: responseModel)
    }
}
