//
//  LeftSideMenuShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Localize_Swift

// MARK: - Business Logic protocols
protocol LeftSideMenuShowBusinessLogic {
    func loadMenuItems(withRequestModel requestModel: LeftSideMenuShowModels.MenuItems.RequestModel)
}

protocol LeftSideMenuShowDataStore {
    var menuItems: [LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem]! { get set }
}

class LeftSideMenuShowInteractor: LeftSideMenuShowBusinessLogic, LeftSideMenuShowDataStore {
    // MARK: - Properties
    var presenter: LeftSideMenuShowPresentationLogic?
    
    // LeftSideMenuShowDataStore protocol implementation
    var menuItems: [LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem]!
    
    
    // MARK: - Business logic implementation
    func loadMenuItems(withRequestModel requestModel: LeftSideMenuShowModels.MenuItems.RequestModel) {
        menuItems = [LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem]()
        
        let itemsTitles = [
            "New order", "Hours of work", "Current order", "Price list", "My orders", "Chat", "Personal data", "Write us", "About us", "Agreement"
        ]
        
        let itemsIcons = [
            "icon-menu-new-order", "icon-menu-working-hours", "icon-menu-current-order", "icon-menu-price-list", "icon-menu-my-orders", "icon-menu-chat", "icon-menu-personal-data", "icon-menu-write-us", "icon-menu-about-us", "icon-menu-agreement"
        ]
        
        let itemsStoryboardNames = [
            "OrderCreate", "XXX", "OrderShow", "PriceListShow", "OrdersShow", "ChatShow", "PersonalDataShow", "WriteUsShow", "AboutShow", "AgreementShow"
        ]

        for i in 0..<itemsTitles.count {
            menuItems.append(LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem(title:             itemsTitles[i].localized(),
                                                                                     iconName:          itemsIcons[i],
                                                                                     storyboardName:    itemsStoryboardNames[i],
                                                                                     cellHeight:        50.0,
                                                                                     cellIdentifier:    "LeftMenuItemCell"))
        }
        
        if Order.firstToChangeStatus == nil {
            menuItems.remove(at: 2)
        }
        
        let responseModel = LeftSideMenuShowModels.MenuItems.ResponseModel()
        presenter?.presentMenuItems(fromResponseModel: responseModel)
    }
}
