//
//  LeftSideMenuShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol LeftSideMenuShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: LeftSideMenuShowModels.Something.ResponseModel)
}

class LeftSideMenuShowPresenter: LeftSideMenuShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: LeftSideMenuShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: LeftSideMenuShowModels.Something.ResponseModel) {
        let viewModel = LeftSideMenuShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
