//
//  LeftSideMenuShowModels.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum LeftSideMenuShowModels {
    // MARK: - Use cases
    enum MenuItems {
        struct RequestModel {
        }
        
        struct ResponseModel {
            struct MenuItem: InitCellParameters {
                let title: String
                let iconName: String
                let storyboardName: String
                let hasShoppingBasketIcon: Bool
                
                // InitCellParameters protocol implementation
                var cellHeight: CGFloat
                var cellIdentifier: String
            }
        }
        
        struct ViewModel {
        }
    }
}
