//
//  LeftSideMenuShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol LeftSideMenuShowBusinessLogic {
    func doSomething(withRequestModel requestModel: LeftSideMenuShowModels.Something.RequestModel)
}

protocol LeftSideMenuShowDataStore {
//     var name: String { get set }
}

class LeftSideMenuShowInteractor: LeftSideMenuShowBusinessLogic, LeftSideMenuShowDataStore {
    // MARK: - Properties
    var presenter: LeftSideMenuShowPresentationLogic?
    var worker: LeftSideMenuShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: LeftSideMenuShowModels.Something.RequestModel) {
        worker = LeftSideMenuShowWorker()
        worker?.doSomeWork()
        
        let responseModel = LeftSideMenuShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
