//
//  OrderShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol OrderShowPresentationLogic {
    func presentUpdateOrderStatus(fromResponseModel responseModel: OrderShowModels.Order.ResponseModel)
}

class OrderShowPresenter: OrderShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: OrderShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentUpdateOrderStatus(fromResponseModel responseModel: OrderShowModels.Order.ResponseModel) {
        let viewModel = OrderShowModels.Order.ViewModel(error: responseModel.error)
        viewController?.displayUpdateOrderStatus(fromViewModel: viewModel)
    }
}
