//
//  OrderShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol OrderShowBusinessLogic {
    func doSomething(withRequestModel requestModel: OrderShowModels.Something.RequestModel)
}

protocol OrderShowDataStore {
//     var name: String { get set }
}

class OrderShowInteractor: OrderShowBusinessLogic, OrderShowDataStore {
    // MARK: - Properties
    var presenter: OrderShowPresentationLogic?
    var worker: OrderShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: OrderShowModels.Something.RequestModel) {
        worker = OrderShowWorker()
        worker?.doSomeWork()
        
        let responseModel = OrderShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
