//
//  MainShowViewController.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SideMenu
import SwiftSpinner
import Localize_Swift

class MainShowViewController: UIViewController, RefreshDataSupport {
    // MARK: - Properties
    fileprivate var order: Order?
    fileprivate var isDeliveryTermShow: Bool = false
    fileprivate var sideMenuManager: SideMenuManager!

    // Background timer
    fileprivate var lastMessageTimer: CustomTimer!
    var backgroundTaskIdentifier: UIBackgroundTaskIdentifier?

    
    // MARK: - IBOutlets
    @IBOutlet weak var myOrderView: UIView!

    @IBOutlet weak var myOrderButton: UIButton! {
        didSet {
            myOrderButton.setTitle("My Order".localized(), for: .normal)
        }
    }
    
    @IBOutlet weak var createOrderButton: UIButton! {
        didSet {
            createOrderButton.setTitle("Create Order".localized(), for: .normal)
        }
    }
    
    @IBOutlet weak var createOrderView: UIView! {
        didSet {
            createOrderView.isHidden = false
        }
    }
    
    @IBOutlet var orderButtonsHeightConstraintsCollection: [NSLayoutConstraint]! {
        didSet {
            _ = orderButtonsHeightConstraintsCollection.map({ $0.constant *= heightRatio })
        }
    }
    
    @IBOutlet var orderButtonsWidthConstraintsCollection: [NSLayoutConstraint]! {
        didSet {
            _ = orderButtonsWidthConstraintsCollection.map({ $0.constant *= widthRatio })
        }
    }

    @IBOutlet weak var buttonsStackViewHeightConstraint: NSLayoutConstraint! {
        didSet {
            buttonsStackViewHeightConstraint.constant *= heightRatio
        }
    }
    
    @IBOutlet weak var buttonsStackViewWidthConstraint: NSLayoutConstraint! {
        didSet {
            buttonsStackViewWidthConstraint.constant *= widthRatio
        }
    }
    
    
    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.addNavigationBarShadow()
        self.loadViewSettings()
        self.setupSideMenu()
    
        // Add Language Observer
        self.registerForCustomAppNotifications(withName: NSNotification.Name(rawValue: LCLLanguageChangeNotification))
        
        // Add Timer Observer
        NotificationCenter.default.addObserver(self,
                                               selector:    #selector(handlerShowDeliveryTermsSceneNotification),
                                               name:        Notification.Name("ShowDeliveryTermsScene"),
                                               object:      nil)
        
        backgroundTaskIdentifier = UIApplication.shared.beginBackgroundTask(expirationHandler: {
            UIApplication.shared.endBackgroundTask(self.backgroundTaskIdentifier!)
        })
        
        // Check Departments in CoreData
        DispatchQueue.main.async {
            if CoreDataManager.instance.readEntities(withName: "Department", withPredicateParameters: nil, andSortDescriptor: nil)!.count == 0 {
                Logger.log(message: "Departments List is empty", event: .Severe)

                RestAPIManager().fetchRequest(withRequestType: .getDepartmentsList([ "laundry_id": Laundry.codeID ], false), andResponseType: ResponseAPIDepartmentsResult.self, completionHandler: { responseAPI in
                    if let result = responseAPI.model as? ResponseAPIDepartmentsResult {
                        // Delete all departments
                        CoreDataManager.instance.deleteEntities(withName: "Department", andPredicateParameters: nil, completion: { success in
                            if success {
                                // Add new departments
                                for model in result.GetDepartmentsResult {
                                    let departmentEntity = CoreDataManager.instance.createEntity("Department") as! Department
                                    departmentEntity.updateEntity(fromResponse: model)
                                    
                                    // Set DepartmentItems
                                    if let items = model.Items, items.count > 0 {
                                        for item in items {
                                            let departmentItemEntity = CoreDataManager.instance.createEntity("DepartmentItem") as! DepartmentItem
                                            
                                            departmentItemEntity.updateEntity(fromResponse: item)
                                            departmentEntity.addToItems(departmentItemEntity)
                                        }
                                    }
                                    
                                    departmentEntity.save()
                                }
                            }
                        })
                    }
                })
            }
            
            else {
                Logger.log(message: "Departments List is full", event: .Severe)
            }
        }
        
        // Core Data: load last Order with empty Delivety Date & Time
        if Order.firstToChangeStatus != nil {
            self.handlerShowDeliveryTermsSceneNotification(Notification.init(name: Notification.Name("ShowDeliveryTermsScene")))
        }
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        // Refresh data of scene
        self.refreshData()
    }
    
    // RefreshDataSupport protocol implementation
    func refreshData() {
        self.loadOrder()
        self.runGetLastClientMessage()
    }
    
    deinit {
        Logger.log(message: "Remove all Observers", event: .Info)
        NotificationCenter.default.removeObserver(self)
    }
        
    
    // MARK: - Custom Functions
    fileprivate func loadViewSettings() {
        self.displayLaundryInfo(withName: Laundry.name, andPhoneNumber: "\(Laundry.phoneNumber ?? "")")
    }
    
    fileprivate func loadOrder() {
        self.order = Order.firstToShow
        self.myOrderView.isHidden = (self.order == nil) ? true : false
    }
    
    fileprivate func setupSideMenu() {
        sideMenuManager = SideMenuManager.default
        let leftSideMenuNC = storyboard!.instantiateViewController(withIdentifier: "LeftSideMenuNC") as! UISideMenuNavigationController
        
        sideMenuManager.menuLeftNavigationController    =   leftSideMenuNC
        sideMenuManager.menuRightNavigationController   =   nil

        sideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        sideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
        
        sideMenuManager.menuWidth           =   270 * widthRatio
        sideMenuManager.menuDismissOnPush   =   true
        sideMenuManager.menuPresentMode     =   .menuSlideIn
        
        let leftSideMenuShowVC              =   leftSideMenuNC.viewControllers.first as! LeftSideMenuShowViewController
        
        sideMenuManager.menuLeftNavigationController    =   leftSideMenuNC
        sideMenuManager.menuRightNavigationController   =   nil

        // Handler left side menu item select
        leftSideMenuShowVC.handlerMenuItemSelectCompletion = { [unowned self] (scene) in
            if let nextScene = scene as? LeftSideMenuShowModels.MenuItems.ResponseModel.MenuItem  {
                DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + dispatchTimeDelay * 3) {
                    leftSideMenuNC.dismiss(animated: true, completion: {})
                    
                    DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + dispatchTimeDelay * 7) {
                        if nextScene.storyboardName == "AgreementShow" {
                            SwiftSpinner.hide()
                            self.createPopover(withName: nextScene.storyboardName, completion: { [unowned self] in
                                self.isDeliveryTermShow = false
                            })
                            
                            self.isDeliveryTermShow = true
                        }
                            
                        else if nextScene.storyboardName != "XXX" {
                            self.show(self.nextViewController(fromStoryboardName: nextScene.storyboardName), sender: nil)
                        }
                        
                        // FIXME: - DELETE AFTER CREATE 'WORKING HOURS SCENE'
                        else {
                            SwiftSpinner.hide()
                        }
                    }
                }
            }
        }
    }
    
    fileprivate func nextViewController(fromStoryboardName storyboardName: String) -> UIViewController {
        let destinationVC = UIStoryboard(name: storyboardName, bundle: nil).instantiateViewController(withIdentifier: storyboardName + "VC")
        
        if storyboardName == "OrderShow", let order = self.order {
            (destinationVC as! OrderShowViewController).saveOrderID(order.orderID)
        }
        
        return destinationVC
    }
    
    fileprivate func runGetLastClientMessage() {
        if self.lastMessageTimer == nil {
            self.lastMessageTimer = CustomTimer.init(withSecondsInterval: 30)
        }
        
        self.lastMessageTimer.resume()
        self.lastMessageTimer.eventHandler = {
            // API
            self.checkNetworkConnection({ connectionSuccess in
                if connectionSuccess {
                    _ = UpdateManager().getLastClientMessage({ [unowned self] (changeOrderStatusSuccess, statusCode) in
                        if changeOrderStatusSuccess {
                            if let status = statusCode, status == 9 || status == 13 {
                                self.showAlertView(withTitle: "Info", andMessage: "Order accepted", needCancel: false, completion: { _ in })
                            }

                            if self.navigationController!.viewControllers.last!.isKind(of: OrderShowViewController.self) {
                                Logger.log(message: "Post Notification to complete change current Order status", event: .Debug)
                                NotificationCenter.default.post(name: Notification.Name("CompleteChangeOrderStatus"), object: nil)
                            }
                        }
                    })
                }
            })
        }
    }

    private func localize() {
        self.createOrderButton.setTitle("Create Order".localized(), for: .normal)
        self.myOrderButton.setTitle("My Order".localized(), for: .normal)
    }
    
    
    // MARK: - Actions
    @IBAction func handlerSideMenuBarButtonTapped(_ sender: UIBarButtonItem) {
        // Show side menu
        Logger.log(message: "Display left side menu", event: .Info)
        present(sideMenuManager.menuLeftNavigationController!, animated: true, completion: nil)
    }
    
    @IBAction func handlerOrderButtonTapped(_ sender: UIButton) {
        self.show(self.nextViewController(fromStoryboardName: (sender.tag == 0) ? "OrderCreate" : "OrderShow"), sender: nil)
    }
    
    @objc func handlerShowDeliveryTermsSceneNotification(_ notification: Notification) {
        if !isDeliveryTermShow && sideMenuManager.menuLeftNavigationController!.isHidden {
            if Order.firstToDelivery != nil {
                DispatchQueue.main.async(execute: {
                    Logger.log(message: "Display DeliveryTermsShow scene", event: .Verbose)
                    self.createPopover(withName: "DeliveryTermsShow", completion: { [unowned self] in
                        self.isDeliveryTermShow = false
                        
                        // Redraw OrderShow scene
                        Logger.log(message: "Post Notification to complete Order delivery change", event: .Debug)
                        NotificationCenter.default.post(name: Notification.Name("CompleteChangeOrderStatus"), object: nil)
                    })
                    
                    self.isDeliveryTermShow = true
                })
            }
        }
    }
    
    override func handlerCustomAppNotification(notification: Notification) {
        self.localize()
    }
}


// MARK: - UISideMenuNavigationControllerDelegate
extension MainShowViewController: UISideMenuNavigationControllerDelegate {
    func sideMenuWillAppear(menu: UISideMenuNavigationController, animated: Bool) {
        Logger.log(message: "SideMenu Appearing! (animated: \(animated))", event: .Info)
    }
    
    func sideMenuDidAppear(menu: UISideMenuNavigationController, animated: Bool) {
        Logger.log(message: "SideMenu Appeared! (animated: \(animated))", event: .Info)
    }
    
    func sideMenuWillDisappear(menu: UISideMenuNavigationController, animated: Bool) {
        Logger.log(message: "SideMenu Disappearing! (animated: \(animated))", event: .Info)
    }
    
    func sideMenuDidDisappear(menu: UISideMenuNavigationController, animated: Bool) {
        Logger.log(message: "SideMenu Disappeared! (animated: \(animated))", event: .Info)
    }
}
