//
//  OrdersShowRouter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol OrdersShowRoutingLogic {
    func routeToOrderShowScene()
}

protocol OrdersShowDataPassing {
    var dataStore: OrdersShowDataStore? { get }
}

class OrdersShowRouter: NSObject, OrdersShowRoutingLogic, OrdersShowDataPassing {
    // MARK: - Properties
    weak var viewController: OrdersShowViewController?
    var dataStore: OrdersShowDataStore?
    
    
    // MARK: - Routing
    func routeToOrderShowScene() {
        let storyboard = UIStoryboard(name: "OrderShow", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "OrderShowVC") as! OrderShowViewController
        var destinationDS = destinationVC.router!.dataStore!
        
        passDataToOrderShowScene(source: dataStore!, destination: &destinationDS)
        navigateToOrderShowScene(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: - Navigation
    func navigateToOrderShowScene(source: OrdersShowViewController, destination: OrderShowViewController) {
        source.show(destination, sender: nil)
    }
    
    
    // MARK: - Passing data
    func passDataToOrderShowScene(source: OrdersShowDataStore, destination: inout OrderShowDataStore) {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.orderID = source.orders?[selectedRow!].orderID
    }
}
