//
//  OrdersShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol OrdersShowBusinessLogic {
    func doSomething(withRequestModel requestModel: OrdersShowModels.Something.RequestModel)
}

protocol OrdersShowDataStore {
//     var name: String { get set }
}

class OrdersShowInteractor: OrdersShowBusinessLogic, OrdersShowDataStore {
    // MARK: - Properties
    var presenter: OrdersShowPresentationLogic?
    var worker: OrdersShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: OrdersShowModels.Something.RequestModel) {
        worker = OrdersShowWorker()
        worker?.doSomeWork()
        
        let responseModel = OrdersShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
