//
//  OrdersShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol OrdersShowPresentationLogic {
    func presentOrders(fromResponseModel responseModel: OrdersShowModels.OrderItem.ResponseModel)
}

class OrdersShowPresenter: OrdersShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: OrdersShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Class deinit", event: .Severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentOrders(fromResponseModel responseModel: OrdersShowModels.OrderItem.ResponseModel) {
        let viewModel = OrdersShowModels.OrderItem.ViewModel()
        viewController?.displayOrders(fromViewModel: viewModel)
    }
}
