//
//  OrdersShowModels.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum OrdersShowModels {
    // MARK: - Use cases
    enum OrderItem {
        struct RequestModel {
            struct DisplayedOrder {
                let createdDate: String
                let status: Int16
                let orderID: Int16
                let price: Float
                let collectionFrom: String
                let collectionTo: String
                let deliveryFrom: String?
                let deliveryTo: String?
            }
        }
        
        struct ResponseModel {
        }
        
        struct ViewModel {
        }
    }
}
