//
//  PersonalDataShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol PersonalDataShowBusinessLogic {
    func doSomething(withRequestModel requestModel: PersonalDataShowModels.Something.RequestModel)
}

protocol PersonalDataShowDataStore {
//     var name: String { get set }
}

class PersonalDataShowInteractor: PersonalDataShowBusinessLogic, PersonalDataShowDataStore {
    // MARK: - Properties
    var presenter: PersonalDataShowPresentationLogic?
    var worker: PersonalDataShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: PersonalDataShowModels.Something.RequestModel) {
        worker = PersonalDataShowWorker()
        worker?.doSomeWork()
        
        let responseModel = PersonalDataShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
