//
//  PersonalDataShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol PersonalDataShowPresentationLogic {
    func presentTerms(fromResponseModel responseModel: PersonalDataShowModels.Client.ResponseModel)
    func presentUpdatePersonalData(fromResponseModel responseModel: PersonalDataShowModels.Client.ResponseModel)
}

class PersonalDataShowPresenter: PersonalDataShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: PersonalDataShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Success", event: .Severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentTerms(fromResponseModel responseModel: PersonalDataShowModels.Client.ResponseModel) {
        let viewModel = PersonalDataShowModels.Client.ViewModel(error: responseModel.error)
        viewController?.displayTerms(fromViewModel: viewModel)
    }
    
    func presentUpdatePersonalData(fromResponseModel responseModel: PersonalDataShowModels.Client.ResponseModel) {
        let viewModel = PersonalDataShowModels.Client.ViewModel(error: responseModel.error)
        viewController?.displayUpdatePersonalData(fromViewModel: viewModel)
    }
}
