//
//  PersonalDataShowModels.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum PersonalDataShowModels {
    // MARK: - Use cases
    enum Client {
        struct RequestModel {
            let params: [String: Any]
        }
        
        struct ResponseModel {
            let error: Error?
        }
        
        struct ViewModel {
            let error: Error?
        }
    }
}
