//
//  WriteUsShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol WriteUsShowPresentationLogic {
    func presentSendMessage(fromResponseModel responseModel: WriteUsShowModels.Data.ResponseModel)
}

class WriteUsShowPresenter: WriteUsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: WriteUsShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSendMessage(fromResponseModel responseModel: WriteUsShowModels.Data.ResponseModel) {
        let viewModel = WriteUsShowModels.Data.ViewModel(error: responseModel.error)
        viewController?.displaySendMessage(fromViewModel: viewModel)
    }
}
