//
//  WriteUsShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 02.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol WriteUsShowBusinessLogic {
    func doSomething(withRequestModel requestModel: WriteUsShowModels.Something.RequestModel)
}

protocol WriteUsShowDataStore {
//     var name: String { get set }
}

class WriteUsShowInteractor: WriteUsShowBusinessLogic, WriteUsShowDataStore {
    // MARK: - Properties
    var presenter: WriteUsShowPresentationLogic?
    var worker: WriteUsShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: WriteUsShowModels.Something.RequestModel) {
        worker = WriteUsShowWorker()
        worker?.doSomeWork()
        
        let responseModel = WriteUsShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
