//
//  ChatShowViewController.swift
//  CleanCase
//
//  Created by msm72 on 08.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol ChatShowDisplayLogic: class {
    func displaySomething(fromViewModel viewModel: ChatShowModels.Something.ViewModel)
}

class ChatShowViewController: UIViewController {
    // MARK: - Properties
    var interactor: ChatShowBusinessLogic?
    var router: (NSObjectProtocol & ChatShowRoutingLogic & ChatShowDataPassing)?
    
    
    // MARK: - IBOutlets
//     @IBOutlet weak var nameTextField: UITextField!
    
    
    // MARK: - Class Initialization
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        setup()
    }

    deinit {
        Logger.log(message: "Success", event: .Severe)
    }
    
    
    // MARK: - Setup
    private func setup() {
        let viewController          =   self
        let interactor              =   ChatShowInteractor()
        let presenter               =   ChatShowPresenter()
        let router                  =   ChatShowRouter()
        
        viewController.interactor   =   interactor
        viewController.router       =   router
        interactor.presenter        =   presenter
        presenter.viewController    =   viewController
        router.viewController       =   viewController
        router.dataStore            =   interactor
    }
    
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.addBackBarButtonItem()
        self.addBasketBarButtonItem(true)
        self.displayLaundryInfo(withName: Laundry.name, andPhoneNumber: "\(Laundry.phoneNumber ?? "")")

        self.loadViewSettings()
    }
    
    
    // MARK: - Custom Functions
    private func loadViewSettings() {
        let requestModel = ChatShowModels.Something.RequestModel()
        interactor?.doSomething(withRequestModel: requestModel)
    }
    
    
    // MARK: - Actions
    @IBAction func tapped(_ sender: Any) {
        UpdateManager.test()
    }
}


// MARK: - ChatShowDisplayLogic
extension ChatShowViewController: ChatShowDisplayLogic {
    func displaySomething(fromViewModel viewModel: ChatShowModels.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
//         nameTextField.text = viewModel.name
    }
}
