//
//  ChatShowModels.swift
//  CleanCase
//
//  Created by msm72 on 08.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Data models
enum ChatShowModels {
    // MARK: - Use cases
    enum Message {
        struct RequestModel {
            let message: String?

            init(message: String? = nil) {
                self.message = message
            }
        }
        
        struct ResponseModel {
            let error: Error?

            init(error: Error? = nil) {
                self.error = error
            }
        }
        
        struct ViewModel {
            let error: Error?

            init(error: Error? = nil) {
                self.error = error
            }
        }
    }
}
