//
//  ChatShowPresenter.swift
//  CleanCase
//
//  Created by msm72 on 08.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol ChatShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: ChatShowModels.Something.ResponseModel)
}

class ChatShowPresenter: ChatShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: ChatShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        Logger.log(message: "Class deinit", event: .Severe)
    }
    

    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: ChatShowModels.Something.ResponseModel) {
        let viewModel = ChatShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
