//
//  ChatShowInteractor.swift
//  CleanCase
//
//  Created by msm72 on 08.02.2018.
//  Copyright (c) 2018 msm72. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol ChatShowBusinessLogic {
    func doSomething(withRequestModel requestModel: ChatShowModels.Something.RequestModel)
}

protocol ChatShowDataStore {
//     var name: String { get set }
}

class ChatShowInteractor: ChatShowBusinessLogic, ChatShowDataStore {
    // MARK: - Properties
    var presenter: ChatShowPresentationLogic?
    var worker: ChatShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: ChatShowModels.Something.RequestModel) {
        worker = ChatShowWorker()
        worker?.doSomeWork()
        
        let responseModel = ChatShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
